///@package io.alkapivo.visu.ui


///@static
///@type {Struct}
global.__VisuTheme = {
  color: {
    accentLight: "#7742b8",
    accent: "#5f398e",
    accentShadow: "#462f63",
    accentDark: "#231832",
    primaryLight: "#455f82",
    primary: "#3B3B53",
    primaryShadow: "#2B2B35",
    primaryDark: "#222227",
    sideLight: "#212129",
    side: "#1B1B20",
    sideShadow: "#141418",
    sideDark: "#0D0D0F",
    button: "#3B3B53",
    buttonHover: "#3c4e66",
    text: "#D9D9D9",
    textShadow: "#878787",
    textFocus: "#ededed",
    textSelected: "#7742b8",
    accept: "#3d9e87",
    acceptShadow: "#368b77",
    deny: "#9e3d54",
    denyShadow: "#6d3c54",
    ruler: "#E64B3D",
    header: "#963271",
    stick: "#5f398e",
    stickHover: "#7742b8",
    stickBackground: "#0D0D0F",
  },
}
#macro VisuTheme global.__VisuTheme


///@type {Map<String, Callable>}
global.__VisuStyles = new Map(String, Callable, {
  "menu-title": {
    label: {
      align: { v: VAlign.BOTTOM, h: HAlign.LEFT },
      font: "font_kodeo_mono_48_bold",
      offset: { x: 48, y: -48 },
      useScale: true,
      useScaleWithOffset: true,
      color: VisuTheme.color.text,
      enableColorWrite: false,
    },
  },
  "menu-statistics": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_12_bold",
      offset: { x: 0, y: 0 },
      useScale: true,
      useScaleWithOffset: true,
      color: VisuTheme.color.text,
      enableColorWrite: false,
    },
  },
  "menu-button-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 48, y: 0 },
      useScale: true,
      useScaleWithOffset: true,
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-button-entry-title": {
    title: {
      align: { v: VAlign.BOTTOM, h: HAlign.LEFT },
      font: "font_kodeo_mono_12_bold",
      color: VisuTheme.color.text,
      offset: { x: 48, y: 0 },
      useScale: true,
      useScaleWithOffset: false,
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundMargin: { top: 8, left: 8, bottom: 0, right: 8 },
      backgroundAlpha: 0.75,
    },
    label: {
      align: { v: VAlign.TOP, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 48, y: 8 },
      useScale: true,
      useScaleWithOffset: true,
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundMargin: { top: 0, left: 8, bottom: 8, right: 8 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-label-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 48 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //backgroundColor: VisuTheme.color.side,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.accentShadow,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8},
      backgroundAlpha: 0.05,
    },
  },
  "menu-button-input-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      outline: true,
      outlineColor: VisuTheme.color.side,
      offset: { x: 48 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    },
    input: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VisuTheme.color.textFocus,
        enableColorWrite: false,
        colorHoverOver: VisuTheme.color.accentLight,
        colorHoverOut: VisuTheme.color.sideDark,
        //backgroundColor: VisuTheme.color.side,
        backgroundAlpha: 0.75,
        backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    },
  },
  "menu-spin-select-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      outline: true,
      outlineColor: VisuTheme.color.side,
      offset: { x: 48 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    },
    previous: {
      sprite: {
        name: "texture_menu_button_previous",
        blend: VisuTheme.color.textFocus,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 0 },
    },
    preview: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VisuTheme.color.textFocus,
        enableColorWrite: false,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundMargin: { top: 8, left: 0, bottom: 8, right: 0 },
      backgroundAlpha: 0.75,
    },
    next: {
      sprite: {
        name: "texture_menu_button_next",
        blend: VisuTheme.color.textFocus,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundMargin: { top: 8, left: 0, bottom: 8, right: 8 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-keyboard-key-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 48 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      outline: true,
      outlineColor: VisuTheme.color.side,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    },
    preview: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.textFocus,
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    }
  },
  "menu-slider-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      outline: true,
      outlineColor: VisuTheme.color.side,
      offset: { x: 48 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 8, left: 8, bottom: 8, right: 8 },
    },
    slider: {
      backgroundColor: VisuTheme.color.side,
      backgroundMargin: { top: 8, bottom: 8, left: -10, right: -8 },
      backgroundAlpha: 0.75,
      pointer: {
        name: "texture_empty",
        scaleX: 0.25,
        scaleY: 0.25,
        blend: VisuTheme.color.accent,
      },
      progress: {
        thickness: 8.0,
        blend: VisuTheme.color.accentLight,
        line: { name: "texture_grid_line_bold" },
        cornerFrom: { name: "texture_empty" },
        cornerTo: { name: "texture_empty" },
      },
      background: {
        thickness: 8.0,
        blend: VisuTheme.color.sideDark,
        line: { name: "texture_grid_line_bold" },
        cornerFrom: { name: "texture_grid_line_bold" },
        cornerTo: { name: "texture_grid_line_bold" },
      },
    },
  },
  "visu-modal": {
    message: {
      color: VisuTheme.color.textFocus,
      font: "font_inter_10_regular",
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
    },
    accept: {
      backgroundColor: VisuTheme.color.acceptShadow,
      label: {
        color: VisuTheme.color.textFocus,
        font: "font_inter_10_regular",
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
      }
    },
    deny: {
      backgroundColor: VisuTheme.color.denyShadow,
      label: {
        color: VisuTheme.color.textFocus,
        font: "font_inter_10_regular",
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
      }
    },
  },
  "text": {
    label: {
      align: { v: VAlign.BOTTOM, h: HAlign.LEFT },
      font: "font_consolas_10_bold",
      color: VisuTheme.color.textFocus,
      outline: true,
      outlineColor: VisuTheme.color.accent,
    },
  },
})
#macro VisuStyles global.__VisuStyles